### ISSUE TITLE
yarn serve编译时报错

### ISSUE THREAD

**Issue by CYF--cc** [kotlindev/gin-demo#3]
node版本10.14.2
npm版本6.4.1
yarn install也是一堆报错，搞不懂什么原因
想问问大佬用的版本都是啥

**Comment by geekdex** [comment]
***@***.***

**Comment by geekdex** [comment]
我的node是v16.15.1，yarn是1.22.19，可能因为网络的原因，你可以换个网络（手机开热点、借别人的宽带之类的）试一试哦，我这里用的是联通

**Comment by geekdex** [comment]
> node版本10.14.2 npm版本6.4.1 yarn install也是一堆报错，搞不懂什么原因 想问问大佬用的版本都是啥

在我印象中，好像之前我用 10.14 也是没有问题

**Comment by CYF--cc** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/10473915/193035490-9bb390ac-f9b9-4020-b2af-cc5f0e289d47.png">
我用mac显示sass不支持操作系统版本，emmmm
顺便问下你的npm版本是多少

**Comment by CYF--cc** [comment]
我用node@10成功了，npm用6.x版本，不能使用yarn，只能用npm run serve，运行成功
